import { useState, type FormEvent } from "react";
import type { LibraryApi } from "./api";
import { InlineError, Modal } from "./Modal";
import { errorMessage, type AcquisitionList, type Settings, type UpdateInfo } from "./types";

export function ListDialog({ list, api, onClose, onSaved }: { list?: AcquisitionList; api: LibraryApi; onClose: () => void; onSaved: (list: AcquisitionList) => Promise<void> }) {
  const [name, setName] = useState(list?.name ?? `${new Date().getFullYear()} 도서 구입 목록`), [year, setYear] = useState(list?.year ?? new Date().getFullYear());
  const [budget, setBudget] = useState(list?.budget ?? 15_000_000), [discount, setDiscount] = useState(list?.discount_percent ?? 0);
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const data = { name: name.trim(), year, budget, discount_percent: discount }; const result = list ? await api.updateList(list.id, data) : await api.createList(data); await onSaved(result); onClose(); } catch (caught) { setError(errorMessage(caught)); } finally { setBusy(false); } }
  return <Modal title={list ? "목록과 예산 설정" : "새 구입 목록"} description="학기나 사업별로 목록을 나누어 관리할 수 있어요." onClose={onClose} busy={busy}><form onSubmit={event => { void save(event); }}><div className="modal-body book-form-grid"><label className="span-2">목록 이름<input required maxLength={120} value={name} onChange={e => setName(e.target.value)} /></label><label>연도<input type="number" min="2000" max="2200" required value={year} onChange={e => setYear(Number(e.target.value))} /></label><label>예산 (원)<input type="number" min="0" step="1" required value={budget} onChange={e => setBudget(Number(e.target.value))} /></label><label>할인율 (%)<input type="number" min="0" max="100" step="0.01" required value={discount} onChange={e => setDiscount(Number(e.target.value))} /></label><p className="field-help">할인 후 한 권의 금액을 원 단위로 반올림하고, 수량을 곱합니다.</p><div className="span-2"><InlineError message={error} /></div></div><footer className="modal-footer"><span className="spacer" /><button type="button" className="button secondary" onClick={onClose} disabled={busy}>취소</button><button type="submit" className="button primary" disabled={busy}>{busy ? "저장 중…" : "저장"}</button></footer></form></Modal>;
}

export function SettingsDialog({ settings, version, api, onClose, onSettings, onRestored }: { settings: Settings; version: string; api: LibraryApi; onClose: () => void; onSettings: (settings: Settings) => void; onRestored: () => Promise<void> }) {
  const [school, setSchool] = useState(settings.school_name), [key, setKey] = useState("");
  const [keyConfigured, setKeyConfigured] = useState(settings.nl_api_key_configured);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const [restoreFile, setRestoreFile] = useState<File | null>(null), [confirmRestore, setConfirmRestore] = useState(false);
  const [update, setUpdate] = useState<UpdateInfo | null>(null);
  async function action(work: () => Promise<void>) { setError(""); setNotice(""); setBusy(true); try { await work(); } catch (caught) { setError(errorMessage(caught)); } finally { setBusy(false); } }
  async function save(event: FormEvent) { event.preventDefault(); await action(async () => { const result = await api.settings({ school_name: school.trim(), ...(key.trim() ? { nl_api_key: key.trim() } : {}) }); onSettings(result); setKeyConfigured(result.nl_api_key_configured); setKey(""); setNotice("설정을 저장했습니다."); }); }
  const updateUrl = update?.url && /^https:\/\/github\.com\//i.test(update.url) ? update.url : undefined;
  return <Modal title="학교 설정" description="이 컴퓨터에서 사용할 정보를 한 번만 입력하세요." onClose={onClose} busy={busy}>
    <div className="modal-body settings-body"><form onSubmit={event => { void save(event); }}><section><h3>우리 학교</h3><label>학교 이름<input value={school} onChange={e => setSchool(e.target.value)} placeholder="예: 햇살초등학교" maxLength={120} /></label><label>국립중앙도서관 인증키 <span className="optional">선택</span><input type="password" value={key} onChange={e => setKey(e.target.value)} placeholder={keyConfigured ? "인증키가 등록되어 있습니다" : "인증키가 있다면 붙여 넣으세요"} autoComplete="new-password" /></label><p className="field-help">등록하지 않아도 Open Library에서 ISBN을 조회할 수 있습니다. 저장한 인증키는 화면과 백업에 표시하지 않습니다.</p><div className="settings-action-row">{keyConfigured && <button type="button" className="text-button" disabled={busy} onClick={() => { void action(async () => { const result = await api.settings({ nl_api_key: "" }); onSettings(result); setKeyConfigured(false); setKey(""); setNotice("인증키를 삭제했습니다."); }); }}>등록한 인증키 삭제</button>}<span className="spacer" /><button type="submit" className="button primary small" disabled={busy}>설정 저장</button></div></section></form>
      <section><h3>자료 백업과 복원</h3><p className="field-help">목록은 이 컴퓨터에 자동 저장됩니다. 다른 컴퓨터로 옮기기 전에는 백업 파일을 보관하세요.</p><div className="settings-action-row"><button className="button secondary small" disabled={busy} onClick={() => { void action(async () => { await api.backup(); setNotice("백업 파일 다운로드를 시작했습니다."); }); }}>백업 파일 저장</button><label className={`file-button ${busy ? "disabled" : ""}`}>백업 불러오기<input type="file" aria-label="복원할 백업 파일" accept=".json" disabled={busy} onChange={e => { setRestoreFile(e.target.files?.[0] ?? null); setConfirmRestore(false); e.target.value = ""; }} /></label></div>
        {restoreFile && <div className="restore-confirm"><strong>{restoreFile.name}</strong><p>이 파일의 자료로 현재 모든 목록과 소장목록, 학교 설정을 바꿉니다. 복원 직전 자료는 자동으로 별도 백업됩니다.</p><label className="check-label"><input type="checkbox" checked={confirmRestore} onChange={e => setConfirmRestore(e.target.checked)} disabled={busy} />현재 자료가 교체되는 것을 확인했습니다.</label><div className="settings-action-row"><button className="button secondary small" onClick={() => setRestoreFile(null)} disabled={busy}>취소</button><button className="button danger small" disabled={busy || !confirmRestore} onClick={() => { void action(async () => { await api.restore(restoreFile); await onRestored(); onClose(); }); }}>이 백업으로 복원</button></div></div>}
      </section>
      <section><div className="section-title"><h3>수서로 <span>v{version}</span></h3><button className="button secondary small" disabled={busy} onClick={() => { void action(async () => { setUpdate(await api.updates()); }); }}>업데이트 확인</button></div><p className="field-help">사서의 선택을 돕는, 내 컴퓨터 속 작은 수서 도구.</p>{update && <div className="update-result" role="status"><strong>{update.available ? `새 버전 ${update.latest_version ?? ""}을 사용할 수 있어요.` : update.message || "현재 최신 버전을 사용하고 있습니다."}</strong>{update.available && <><p className="field-help">{update.message}</p><div className="settings-action-row"><button className="button primary small" disabled={busy} onClick={() => { void action(async () => { const result = await api.installUpdate(); if (!result.started) throw new Error("설치 프로그램을 시작하지 못했습니다. 다운로드 링크를 이용해 주세요."); setNotice("설치 프로그램을 시작했습니다. 설치 창의 안내를 따라 주세요."); }); }}>업데이트 설치</button>{updateUrl && <a className="text-button" href={updateUrl} target="_blank" rel="noreferrer">설치 파일 다운로드 ↗</a>}</div></>}</div>}</section>
      <InlineError message={error} />{notice && <p className="inline-success" role="status">{notice}</p>}
    </div><footer className="modal-footer"><p className="field-help">개인용 · 자동 저장</p><span className="spacer" /><button className="button secondary" onClick={onClose} disabled={busy}>닫기</button></footer>
  </Modal>;
}
